-- ============================================================
-- V6 – Snowflake ID: remove sequence defaults from app-managed columns
--
-- CONTEXT
-- -------
-- The application now generates NUME_LLAMADA and CADEVEN_NUME_EVENTO
-- using the Snowflake algorithm (SnowflakeGenerator.cs).
--
-- Snowflake IDs embed a NodeId in bits 12-21:
--   Main  node (NodeId=1) → IDs unique to this node
--   Edge  node (NodeId=2) → IDs unique to this node
--
-- This makes it physically impossible for two nodes to produce the
-- same ID, so Main ↔ Edge merges are always safe.
--
-- WHAT THIS SCRIPT DOES
-- ---------------------
-- 1. Removes the DEFAULT nextval('seq_pedidos')    from cad_pedidos.nume_llamada
-- 2. Removes the DEFAULT nextval('seq_eventos')    from the event column
--    in cad_pedidos_canales (if a default was set there).
-- 3. Keeps both sequences in the database for rollback safety — they are
--    simply no longer called by the application.
--
-- Apply to every CAD tenant database.
-- ============================================================

-- 1. Drop sequence default from the call-number column.
--    The app now supplies the value; the column must NOT auto-generate one.
ALTER TABLE cad_pedidos
    ALTER COLUMN nume_llamada DROP DEFAULT;

COMMENT ON COLUMN cad_pedidos.nume_llamada IS
    'Unique call ID. Generated by SnowflakeGenerator (node-partitioned 64-bit ID). '
    'seq_pedidos is retained for rollback but is no longer used by the application.';

-- 2. Drop sequence default from the event-number column (if present).
--    Some installations may not have a default here; IF EXISTS makes it idempotent.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE  table_name  = 'cad_pedidos_canales'
          AND  column_name = 'cadeven_nume_evento'
          AND  column_default IS NOT NULL
    ) THEN
        ALTER TABLE cad_pedidos_canales
            ALTER COLUMN cadeven_nume_evento DROP DEFAULT;
    END IF;
END $$;

COMMENT ON COLUMN cad_pedidos_canales.cadeven_nume_evento IS
    'Event number. Generated by SnowflakeGenerator (node-partitioned 64-bit ID). '
    'seq_eventos is retained for rollback but is no longer used by the application.';

-- ── Verify ───────────────────────────────────────────────────────────────────
-- Run this SELECT after applying; both column_default values must be NULL.
--
-- SELECT table_name, column_name, column_default
-- FROM   information_schema.columns
-- WHERE  table_name  IN ('cad_pedidos', 'cad_pedidos_canales')
--   AND  column_name IN ('nume_llamada', 'cadeven_nume_evento');
