version: '3.8'

services:
  # Backend API .NET 8
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: secad-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Oracle=Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=SRVDBDESA.policia.gov.co)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=TELEPOL_TEST)));User ID=USR_DEV_TEST;Password=Policia2027*+
      - Jwt__Key=YourSuperSecretKeyAtLeast32Characters!
      - Jwt__Issuer=oftic.api
      - Jwt__Audience=oftic.api
      - Storage__SliderPath=/app/uploads/sliders
      - Storage__RadioLogoPath=/app/uploads/radio
      - SECAD_BRANDING_PATH=/app/uploads/branding
    volumes:
      - backend-uploads:/app/uploads
    restart: unless-stopped
    networks:
      - secad-network

  # Frontend Angular con Nginx
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: secad-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - secad-network

volumes:
  backend-uploads:
    driver: local

networks:
  secad-network:
    driver: bridge
