<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\oftic.cl\Comun.csproj" />
    <ProjectReference Include="..\oftic.dl\Datos.csproj" />
    <ProjectReference Include="..\oftic.sl\Servicios.csproj" />
  </ItemGroup>

</Project>
